#!/usr/bin/env python3
"""Generate profiles/<plan>/ from templates/ and the tables below.

Model and effort choices live only in PROFILES, and role prompts live only in
templates/roles/, so the plans can never drift apart.

  python3 scripts/build_profiles.py          # regenerate profiles/
  python3 scripts/build_profiles.py --check  # exit 1 if profiles/ is stale
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "templates"
PROFILES_DIR = ROOT / "profiles"

ASTRA = "gpt-6-astra"
LUNA = "gpt-5.6-luna"
SKILL_NAME = "sage-orchestrator"

ROLES = {
    "scout": {
        "sandbox": "read-only",
        "blurb": "read-only mapping",
        "description": "Read-only reconnaissance. Use before implementation to map code paths, "
        "symbols, configuration, and existing tests.",
    },
    "builder": {
        "sandbox": "workspace-write",
        "blurb": "bounded implementation",
        "description": "Implementation subagent for one bounded contract with named file ownership "
        "and acceptance criteria.",
    },
    "verifier": {
        "sandbox": "workspace-write",
        "blurb": "tests and reproduction",
        "description": "Independent verification. Use to reproduce failures, run targeted tests, "
        "and report pass/fail with exact evidence.",
    },
    "scholar": {
        "sandbox": "read-only",
        "blurb": "external facts",
        "description": "Read-only technical research for version-specific APIs, framework "
        "behavior, and dependency facts from primary sources.",
    },
    "critic": {
        "sandbox": "read-only",
        "blurb": "independent review",
        "description": "Read-only reviewer of a finished diff: correctness, regressions, security, "
        "data integrity, concurrency, and missing tests.",
    },
}

PROFILES = {
    "pro": {
        "title": "Pro",
        "root": (ASTRA, "medium"),
        "workers": (LUNA, "max"),
        "critic": (ASTRA, "low"),
        "threads": 4,
        "note": "Astra plans and reviews; Luna does the heavy lifting at max reasoning.",
    },
    "plus": {
        "title": "Plus",
        "root": (LUNA, "max"),
        "workers": (LUNA, "medium"),
        "critic": (ASTRA, "low"),
        "threads": 3,
        "note": "The root is the largest line item, so it runs on Luna. Astra is kept "
        "for one short, independent review.",
    },
    "lite": {
        "title": "Lite",
        "root": (LUNA, "medium"),
        "workers": (LUNA, "low"),
        "critic": (LUNA, "medium"),
        "threads": 2,
        "note": "Cheapest setup: everything on Luna with low concurrency. Use for routine "
        "work or when you are close to a rate limit.",
    },
}

HEADER = "# Generated by scripts/build_profiles.py. Edit the templates or PROFILES there, not this file.\n"


def toml_string(value: str) -> str:
    # JSON string escaping is a valid subset of TOML basic strings.
    return json.dumps(value, ensure_ascii=False)


def toml_multiline(value: str) -> str:
    if '"""' in value:
        raise ValueError('role templates must not contain """')
    return '"""\n' + value.replace("\\", "\\\\").rstrip("\n") + '\n"""'


def role_model(profile: dict, role: str) -> tuple[str, str]:
    return profile["critic"] if role == "critic" else profile["workers"]


def render_config(plan: str, profile: dict) -> str:
    root_model, root_effort = profile["root"]
    sub_model, sub_effort = profile["workers"]
    return f"""{HEADER}#
# codesage-orchestrator: {profile['title']} profile
# {profile['note']}
#
# Project scope: <repo>/.codex/config.toml (Codex loads it for trusted projects only)
# Global scope:  merge these keys into ~/.codex/config.toml; do not overwrite that file.

# Root / orchestrator
model = {toml_string(root_model)}
model_reasoning_effort = {toml_string(root_effort)}

approval_policy = "on-request"
sandbox_mode = "workspace-write"

[agents]
enabled = true
max_concurrent_threads_per_session = {profile['threads']}

# Used only by spawns that do not name a role; named roles pin their own model.
default_subagent_model = {toml_string(sub_model)}
default_subagent_reasoning_effort = {toml_string(sub_effort)}
"""


def render_role(role: str, profile: dict) -> str:
    spec = ROLES[role]
    model, effort = role_model(profile, role)
    instructions = (TEMPLATES / "roles" / f"{role}.md").read_text(encoding="utf-8")
    return f"""{HEADER}name = {toml_string(role)}
description = {toml_string(spec['description'])}

model = {toml_string(model)}
model_reasoning_effort = {toml_string(effort)}
sandbox_mode = {toml_string(spec['sandbox'])}

developer_instructions = {toml_multiline(instructions)}
"""


def render_skill(profile: dict) -> str:
    root_model, root_effort = profile["root"]
    rows = [("root", root_model, root_effort, "plans, integrates, verifies")]
    rows += [(role, *role_model(profile, role), ROLES[role]["blurb"]) for role in ROLES]
    width = max(len(model) for _, model, _, _ in rows)
    topology = "\n".join(
        f"{name:<9} {model:<{width}}  {effort:<6}  {blurb}" for name, model, effort, blurb in rows
    )
    description = (
        f"Orchestrate multi-step Codex coding work ({profile['title']} profile: {root_model} "
        f"{root_effort} root, {profile['workers'][0]} {profile['workers'][1]} execution roles, "
        f"{profile['critic'][0]} {profile['critic'][1]} critic). Use for multi-file features, "
        "cross-component debugging, repo-wide changes, parallel workstreams, or when the user "
        "asks for subagents. Skip for single-file edits and plain questions."
    )
    text = (TEMPLATES / "skill.md").read_text(encoding="utf-8")
    for key, value in {
        "description": description,
        "title": profile["title"],
        "topology": topology,
        "threads": str(profile["threads"]),
    }.items():
        text = text.replace("{{" + key + "}}", value)
    if "{{" in text:
        raise ValueError("unreplaced placeholder in templates/skill.md")
    return text


def render_all() -> dict[Path, str]:
    files: dict[Path, str] = {}
    for plan, profile in PROFILES.items():
        base = Path(plan)
        files[base / "codex" / "config.toml"] = render_config(plan, profile)
        for role in ROLES:
            files[base / "codex" / "agents" / f"{role}.toml"] = render_role(role, profile)
        files[base / "agents" / "skills" / SKILL_NAME / "SKILL.md"] = render_skill(profile)
    return files


def existing_files() -> set[Path]:
    if not PROFILES_DIR.is_dir():
        return set()
    return {p.relative_to(PROFILES_DIR) for p in PROFILES_DIR.rglob("*") if p.is_file()}


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify profiles/ is up to date without writing")
    args = parser.parse_args(argv)

    files = render_all()
    stale = sorted(
        str(rel)
        for rel, content in files.items()
        if not (PROFILES_DIR / rel).is_file() or (PROFILES_DIR / rel).read_text(encoding="utf-8") != content
    )
    extra = sorted(str(rel) for rel in existing_files() - set(files))

    if args.check:
        for rel in stale:
            print(f"stale: profiles/{rel}", file=sys.stderr)
        for rel in extra:
            print(f"unexpected: profiles/{rel}", file=sys.stderr)
        if stale or extra:
            print("Run: python3 scripts/build_profiles.py", file=sys.stderr)
            return 1
        print(f"profiles/ is up to date ({len(files)} files)")
        return 0

    if PROFILES_DIR.exists():
        shutil.rmtree(PROFILES_DIR)
    for rel, content in files.items():
        path = PROFILES_DIR / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
    print(f"Wrote {len(files)} files to profiles/ ({', '.join(PROFILES)})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
